"""initial_migration

Revision ID: f29abf92690b
Revises: 
Create Date: 2026-05-11 15:17:32.120593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f29abf92690b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('CLERK', 'MANAGER', name='role', create_constraint=True), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_employees_full_name'), 'employees', ['full_name'], unique=False)
    op.create_table('patrons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('productions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productions_name'), 'productions', ['name'], unique=False)
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seat_row', sa.String(length=50), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('VIP', 'REGULAR', name='seatcategory', create_constraint=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seat_row', 'seat_number', name='uq_seatrow_seatnumber')
    )
    op.create_table('performances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('performance_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('production_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performances_performance_datetime'), 'performances', ['performance_datetime'], unique=False)
    op.create_index(op.f('ix_performances_production_id'), 'performances', ['production_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('SOLD', 'CANCELLED', name='ticketstatus', create_constraint=True), nullable=False),
    sa.Column('patron_id', sa.Integer(), nullable=False),
    sa.Column('performance_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('clerk_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clerk_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patron_id'], ['patrons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performance_id'], ['performances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('performance_id', 'seat_id', name='uq_performance_seat')
    )
    op.create_index(op.f('ix_tickets_patron_id'), 'tickets', ['patron_id'], unique=False)
    op.create_index(op.f('ix_tickets_performance_id'), 'tickets', ['performance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_performance_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_patron_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_performances_production_id'), table_name='performances')
    op.drop_index(op.f('ix_performances_performance_datetime'), table_name='performances')
    op.drop_table('performances')
    op.drop_table('seats')
    op.drop_index(op.f('ix_productions_name'), table_name='productions')
    op.drop_table('productions')
    op.drop_table('patrons')
    op.drop_index(op.f('ix_employees_full_name'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
